# Generated by Django 3.0.3 on 2021-11-20 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=25)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingFormINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=50)),
                ('address_line_one', models.CharField(max_length=100)),
                ('address_line_two', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('provinces', models.CharField(max_length=50)),
                ('phone_code', models.CharField(max_length=5)),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('website', models.CharField(blank=True, max_length=500)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Vaccine')),
            ],
        ),
    ]
