# Generated by Django 3.2.9 on 2021-11-26 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=50)),
                ('address_line_one', models.CharField(max_length=100)),
                ('address_line_two', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('provinces', models.CharField(max_length=50)),
                ('phone_code', models.CharField(choices=[('CA', '+1'), ('IN', '+91')], default='CA', max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAppointBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_line_one', models.CharField(max_length=100)),
                ('address_line_two', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('provinces', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_code', models.CharField(choices=[('CA', '+1'), ('IN', '+91')], default='CA', max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('health_card', models.ImageField(upload_to='images/')),
                ('which_dose', models.CharField(choices=[('FD', 'First Dose'), ('SD', 'Second Dose')], max_length=2)),
                ('vaccine_name', models.CharField(choices=[('MV', 'Moderna vaccine'), ('PV', 'Pfizer vaccine'), ('JV', 'Johnson and Johnson vaccine'), ('AV', 'Astrazeneca vaccine')], max_length=2)),
                ('choose_date', models.DateTimeField()),
                ('got_dose', models.BooleanField(default=False)),
                ('mossed_dose', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_for', models.CharField(max_length=500)),
                ('vaccine_name', models.CharField(choices=[('MV', 'Moderna vaccine'), ('PV', 'Pfizer vaccine'), ('JV', 'Johnson and Johnson vaccine'), ('AV', 'Astrazeneca vaccine')], max_length=2)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
            ],
        ),
    ]
