# Generated by Django 3.0.3 on 2021-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_name',
            field=models.CharField(choices=[('MV', 'Moderna vaccine'), ('PV', 'Pfizer vaccine'), ('JV', 'Johnson and Johnson vaccine'), ('AV', 'Astrazeneca vaccine')], max_length=2),
        ),
    ]
