# Generated by Django 3.0.3 on 2021-11-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211120_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingforminfo',
            name='phone_code',
            field=models.CharField(choices=[('CA', '+1'), ('IN', '+91')], default='CA', max_length=5),
        ),
    ]
